name: Print Number

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Enter a number"
        required: true

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print number
        run: |
          echo "Number: ${{ github.event.inputs.number }}"
