name: PrintP Number

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Enter a number"
        required: true
        default: "42"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Python
        run: python3 main.py "${{ github.event.inputs.number }}"

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.txt
